Resilientcapitalstockdjango-master/resilientcapital/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from resilientcapitalapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^resilientcapitalapp/',include('resilientcapitalapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^sp50dma/$', views.plot_view, name='sp50dma'),
    url(r'^sp200dma/$', views.plot_view200dma, name='sp200dma'),
    url(r'^spissues/$', views.plot_spissuesview, name='spissues'),
    url(r'^sprsi70/$', views.plot_sprsi70view, name='sprsi70'),
    url(r'^sprsi30/$', views.plot_sprsi30view, name='sprsi30'),
    url(r'^spupperbolinger/$', views.plot_spupperbolingerview, name='spupperbolinger'),
    url(r'^splowerbolinger/$', views.plot_splowerbolingerview, name='splowerbolinger'),
    url(r'^sp52weekshigh/$', views.plot_sp52weekshighview, name='sp52weekshigh'),
    url(r'^sp52weekslow/$', views.plot_sp52weekslowview, name='sp52weekslow'),
    url(r'^sphighlow/$', views.plot_sphighlowview, name='sphighlow'),
    url(r'^sp24weekshigh/$', views.plot_sp24weekshighview, name='sp24weekshigh'),
    url(r'^sp24weekslow/$', views.plot_sp24weekslowview, name='sp24weekslow'),
    url(r'^spcorrection/$', views.plot_spcorrectionview, name='spcorrection'),
    url(r'^spbearmarket/$', views.plot_spbearmarketview, name='spbearmarket'),
    url(r'^nasdaq50dma/$', views.plot_view50dma, name='nasdaq50dma'),
    url(r'^nasdaq200dma/$', views.plot_nasdaq200dmaview, name='nasdaq200dma'),
    url(r'^nasdaqissues/$', views.plot_nasdaqissuesview, name='nasdaqissues'),
    url(r'^nasdaqrsi70/$', views.plot_nasdaqrsi70view, name='nasdaqrsi70'),
    url(r'^nasdaqrsi30/$', views.plot_nasdaqrsi30view, name='nasdaqrsi30'),
    url(r'^nasdaqupperbolinger/$', views.plot_nasdaqupperbolingerview, name='nasdaqupperbolinger'),
    url(r'^nasdaqlowerbolinger/$', views.plot_nasdaqplowerbolingerview, name='nasdaqlowerbolinger'),
    url(r'^nasdaq52weekshigh/$', views.plot_nasdaq52weekshighview, name='nasdaq52weekshigh'),
    url(r'^nasdaq52weekslow/$', views.plot_nasdaq52weekslowview, name='nasdaq52weekslow'),
    url(r'^nasdaqhighlow/$', views.plot_nasdaqhighlowview, name='nasdaqhighlow'),
    url(r'^nasdaq24weekshigh/$', views.plot_nasdaq24weekshighview, name='nasdaq24weekshigh'),
    url(r'^nasdaq24weekslow/$', views.plot_nasdaq24weekslowview, name='nasdaq24weekslow'),
]

Resilientcapitalstockdjango-master/resilientcapitalapp/urls.py
from django.conf.urls import url
from django.urls import path
from resilientcapitalapp import views
# SET THE NAMESPACE!
app_name = 'resilientcapitalapp'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    #path('', views.index, name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^home/$',views.save_datas,name='home'),
    url(r'^sp50dma/$', views.plot_view, name='sp50dma'),

]

Resilientcapitalstockdjango-master/templates/graph.html
{% extends "base.html" %}

{% block extrahead %}
    <!--# <script src="http://code.highcharts.com/highcharts.js"></script> Load in jQuery and HighCharts -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.6/js/highstock.js"></script>

{% endblock %}

{% block body_block %}
<div id="container"></div>
<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/data.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
<script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
<script>
  Highcharts.chart('container',{
    "title": {
        "text": "% of S&P 500 members above their 50 dma",
        "align": "left",
        "x": 10
     },
    "subtitle": {
        "text": "",
        "align": "left",
        "x": 10
    },
    "plotOptions": {
        "series": {
        "allowPointSelect": true,
        "states": {
            "select": {
             "color": "#EFFFEF",
            "borderColor": "black",
            "dashStyle": "dot"
         }
        },
        "marker": {
            "enabled": false
        },
        "lineWidth": 2,
        "events": {
            "legendItemClick": "function(e){e.preventDefault()}"
        }
        }
    },
    "exporting": {},
    "credits": {
     "text": "",
        "href": "",
        "enabled": false
    },

    "colors": [
        "#235A61",
        "#DD495E",
        "#2A2383",
        "#F2C60E",
        "#24CBE5",
        "#64E572",
        "#FF9655",
        "#FFF263",
        "#6AF9C4"
    ],
    "legend": {
        "align": "left",
        "verticalAlign": "top",
        "itemMarginBottom": 10,
        "x": 0,
        "symbolRadius": 2
    },
    "series": [
     {
        "type": "line",
        "data": {{ sp500_series }},
        "name": "S&P 500",
        "tooltip": {
                    valueDecimals: 2
               }
        },
        {
         "name": "Chicago Fed",
        "yAxis": 1,
        "type": "line",
        "allowExtendPlayingField": false,
        "y": -30,
        "binsNumber": "square-root",
        "data": {{ dma50_series }},

            tooltip: {
                    valueDecimals: 2
             }
        }
    ],
    "chart": {
        "type": "line",
        "width": 800,
        "height": 600,
     "zoomType": "x"
    },
     "stockTools": {
        "gui": {
        "buttons": [
         "simpleShapes",
            "lines",
            "crookedLines"
        ],
        "enabled": false
        }
    },
    "navigation": {
        "events": {
        "showPopup": "function(e){this.chart.indicatorsPopupContainer||(this.chart.indicatorsPopupContainer=document.getElementsByClassName(\"highcharts-popup-indicators\")[0]),this.chart.annotationsPopupContainer||(this.chart.annotationsPopupContainer=document.getElementsByClassName(\"highcharts-popup-annotations\")[0]),\"indicators\"===e.formType?this.chart.indicatorsPopupContainer.style.display=\"block\":\"annotation-toolbar\"===e.formType&&(this.chart.activeButton||(this.chart.currentAnnotation=e.annotation,this.chart.annotationsPopupContainer.style.display=\"block\")),this.popup&&(t=this.popup)}",
        "closePopup": "function(){this.chart.annotationsPopupContainer.style.display=\"none\",this.chart.currentAnnotation=null}",
        "selectButton": "function(e){var t=e.button.className+\" highcharts-active\";e.button.classList.contains(\"highcharts-active\")||(e.button.className=t,this.chart.activeButton=e.button)}",
        "deselectButton": "function(e){e.button.classList.remove(\"highcharts-active\"),this.chart.activeButton=null}"
        },
        "bindingsClassName": "tools-container"
    },
    "xAxis": {
        "minPadding": 0,
        "maxPadding": 0,
        "overscroll": 0,
        "ordinal": true,
        "title": {
        "text": null
        },
        "labels": {
        "overflow": "justify"
     },
        "showLastLabel": true,
        "type": "datetime",
        "categories": null,
        "startOnTick": false,
        "endOnTick": false,
        "index": 0,
        "isX": true,
        "tickWidth": "0",
        "categories:{{ date }},
    },
    "yAxis": [
        {
        "labels": {
          "y": -2
        },
        "opposite": true,
        "showLastLabel": false,
        "title": {
          "text": null
         },
         "index": 0,
        "height": 200,
         "top": 60
        },
        {
        "labels": {
         "y": -2
        },
         "opposite": true,
        "showLastLabel": false,
        "title": {
            "text": null
        },
        "lineWidth": 0,
        "top": 280,
        "height": 200,
        "index": 1
        }
    ],
    "labels": {
     "items": []
    },
    "responsive": {
        "rules": []
    },
    "rangeSelector": {
        "selected": 5,
        "buttons": [
         {
         "count": 1,
            "text": "1m",
            "type": "month"
        },
        {
            "type": "month",
            "count": 3,
            "text": "3m"
        },
         {
            "type": "month",
            "count": 6,
            "text": "6m"
        },
        {
            " type": "ytd",
            "text": "YTD"
        },
        {
            "type": "year",
            "count": 1,
            "text": "1Y"
        },
        {
            "type": "year",
            "count": 3,
            "text": "3Y"
        },
        {
         "type": "all",
            "text": "All"
        }
        ]
    },
     "annotations": []
  })

   </script>

{% endblock %}

Resilientcapitalstockdjango-master/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>

<body>
<h1>HOME</h1>

<table>
    <tr>
        <th>Date</th>
        <th>sp500</th>
        <th>dma50</th>

    </tr>
    {% for item in query_results %}
        <tr>
            <td>{{ item.date }}</td>
            <td>{{ item.sp500 }}</td>
            <td>{{ item.dma50 }}</td>

        </tr>
    {% endfor %}
</table>

</body>
</html>

Resilientcapitalstockdjango-master/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'resilientcapitalapp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

Resilientcapitalstockdjango-master/templates/nasdaq200dma.html
{% extends "base.html" %}

{% block extrahead %}
    <!--# <script src="http://code.highcharts.com/highcharts.js"></script> Load in jQuery and HighCharts -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.6/js/highstock.js"></script>

{% endblock %}

{% block body_block %}
<div class="page-title">
                        <h1>
                           % of NASDAQ 100 members above their 200 dma
                        </h1>
</div>
<div id="container" style="height: 100%; width:90%";position:absolute;></div>

<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/data.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
<script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
<script>
const timezone = new Date().getTimezoneOffset()
  Highcharts.setOptions({
    global: {
        timezoneOffset: timezone
    }
});
  Highcharts.stockChart('container', {
      chart: {
          zoomType: 'x',
          type: 'line',
          marginTop: 50,
          height: 700,
          width:1000
      },
      credits: {
      enabled: false
    },

      rangeSelector: {
            allButtonsEnabled: true,
            selected: 2
        },
      title: {
          text: '% of NASDAQ 100 members above their 200 dma'
      },
       xAxis: {


      type: 'datetime',
      dateTimeLabelFormats: {

            day: '%e. %b',
            week: '%e. %b',
            month: '%b \'%y',
            year: '%Y'
        },
    },
    tooltip: {
        xDateFormat: '%Y-%m-%d',
        shared: true
    },


      yAxis: [{
        lineWidth: 0,
        height :150,
        opposite: true,
        tickposition:'outside',
        top:150,
        visible:true,
        labels:{
                align:'right',
                x:10
            },

      }, {
        lineWidth: 0,
        height :200,
        opposite: true,
        tickposition:'outside',
        top :300,
        visible:true,
        labels:{
                align:'right',
                x:10
            },

      }],

      series: [ {
          yAxis: 1,
          xAxis:0,
          y :-30,
          name: '% of NASDAQ 100 members above their 200 dma',
          data: {{ dma200_series | safe }},
          color: 'red',
          showInLegend:true,
          tooltip: {
                valueDecimals: 2
            }

      },{
          yAxis: 0,
          name: 'NASDAQ 100',
          data: {{ sp500_series | safe}},
          color: 'green',
          showInLegend:true,
          tooltip: {
                valueDecimals: 2
            }

      }]
  });


</script>
<div id="container1" style="height: 100%; width:90%";position:absolute;>
<div class='col-md-12';>
    <div class="panel panel-default";style="height: 400; width:100";>
        <div class="panel-heading">
            <h3 class="panel-title">Indicator Details and Other Charts</h3>
        </div>
        <div class="panel-body">
            <div class="tabbable-line">
                <ul class="nav nav-tabs">

        <li class="#active">
            <a href="#detail" data-toggle="tab" aria-expanded="true">
                Indicator Detail
            </a>
        </li>

</ul>
<div class="tab-content">
    <div class="tab-pane fade active in" id="detail">
           <div class="well">
                 <h4>
                     <b>
                           Time Frame:

                                Medium-Term

                        </b>
                    </h4>
                    <h4>
                        <b>
                            Update Schedule:

                                Daily by 6:00 PM EST

                        </b>
                    </h4>

                    <h4>
                        <b>
                            Source:

                                Resilient Capital

                        </b>
                    </h4>

                </div>


        <h4>
            <b>Construction:</b>
        </h4>
        <p>The Smart Money Confidence and Dumb Money Confidence indices are a unique innovation that allows subscribers to see, in one quick glance, what the "good" market timers are doing with their money compared to what "bad" market timers are doing. </p>

<p>Our Confidence indices use mostly real-money gauges - there are few opinions involved here.
Generally, we want to follow the Smart Money traders when they reach an extreme - we want to bet on a market rally when they are confident of rising prices, and we want to be short (or in cash) when they are expecting a market decline. The higher the confidence number, the more aggressively we should be looking for higher prices.</p>

<p>Examples of some Smart Money indicators include the OEX put/call and open interest ratios, commercial hedger positions in the equity index futures, and the current relationship between stocks and bonds.</p>

<p>In contrast to the Smart Money, we want to do the opposite of what the Dumb Money is doing when they are at an extreme.  These traders have proven themselves over history to be bad at market timing.  They get very bullish after a market rally, and bearish after a market fall.  By the time the majority of them catch on to a trend, it?s too late - the trend is about to reverse.  It tells us how confident we should be in selling the market.
 </p>
<p>Examples of some Dumb Money indicators include the equity-only put/call ratio, the flow into and out of the Rydex series of index mutual funds, and small speculators in equity index futures contracts. We also chart the spread between the Smart Money and Dumb Money.  This gives us a quick view of the difference between the two groups of traders.  Because the "dumb money" follows trends, and the "smart money" generally goes against trends, the "dumb money" is usually correct during the meat of the trend.  So when the Dumb Money Confidence is higher than the Smart Money Confidence, that means sentiment is positive.</p>

<p>When it becomes too positive, however, then sentiment has reached an extreme, and stocks often run into trouble.  This usually happens because the Dumb Money rises above 60%, and the Smart Money drops below 40%.  That is a warning sign for stocks.</p>

<p>When the Dumb Money is below the Smart Money, then sentiment is negative and stocks are usually struggling.  It's best to be defensive at times like this.  However, when sentiment becomes too negative, then stocks are often poised to rally over the next 1-3 months.  This usually occurs because the Dumb Money has dropped below 40% and the Smart Money has risen above 60%.</p>

<p>What is considered "smart" is simply based on an indicator's historical record at extremes.  If an indicator is usually showing excessive pessimism near a market peak, and excessive optimism near a market bottom, then that indicator will be included in our Smart Money calculation.  And if it consistently shows too much pessimism near a low and too much optimism near a high, it will be considered Dumb Money.
</p>
<p>Confidence indices are presented on a scale of 0% to 100%.  When the Smart Money Confidence is at 100%, it means that those most correct on market direction are 100% confident of a rising market?and we want to be right alongside them.  When it is at 0%, it means that these good market timers are 0% confident in a rally, and we want to be in cash or even short when confidence is very low. </p>

<p>We can use the Dumb Money Confidence in a similar, but opposite, manner.  For example, if the Dumb Money Confidence is at 100%, then that means that these bad market timers are supremely confident in a market rally.  And history suggests that when these traders are confident, we should be very, very worried that the market is about to decline.  When the Dumb Money Confidence is at 0%, then from a contrary perspective we should be concentrating on the long side, expecting these traders to be wrong again and the market to rally. </p>

<p>In practice, our Confidence Indexes rarely get below 30% or above 70%. </p>

    </div>
</div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

Resilientcapitalstockdjango-master/templates/nasdaq24weekshigh.html
{% extends "base.html" %}

{% block extrahead %}
    <!--# <script src="http://code.highcharts.com/highcharts.js"></script> Load in jQuery and HighCharts -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.6/js/highstock.js"></script>

{% endblock %}

{% block body_block %}
<div class="page-title">
                        <h1>
                           % of NASDAQ 100 members at a 24 week high
                        </h1>
</div>
<div id="container" style="height: 100%; width:90%";position:absolute;></div>

<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/data.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
<script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
<script>
const timezone = new Date().getTimezoneOffset()
  Highcharts.setOptions({
    global: {
        timezoneOffset: timezone
    }
});
  Highcharts.stockChart('container', {
      chart: {
          zoomType: 'x',
          type: 'line',
          marginTop: 50,
          height: 700,
          width:1000
      },
      credits: {
      enabled: false
    },

      rangeSelector: {
            allButtonsEnabled: true,
            selected: 2
        },
      title: {
          text: '% of NASDAQ 100 members at a 24 week high'
      },
       xAxis: {


      type: 'datetime',
      dateTimeLabelFormats: {

            day: '%e. %b',
            week: '%e. %b',
            month: '%b \'%y',
            year: '%Y'
        },
    },
    tooltip: {
        xDateFormat: '%Y-%m-%d',
        shared: true
    },


      yAxis: [{
        lineWidth: 0,
        height :150,
        opposite: true,
        tickposition:'outside',
        top:150,
        visible:true,
        labels:{
                align:'right',
                x:10
            },

      }, {
        lineWidth: 0,
        height :200,
        opposite: true,
        tickposition:'outside',
        top :300,
        visible:true,
        labels:{
                align:'right',
                x:10
            },

      }],

      series: [ {
          yAxis: 1,
          xAxis:0,
          y :-30,
          name: '% of NASDAQ 100 members at a 24 week high',
          data: {{ dma200_series | safe }},
          color: 'red',
          showInLegend:true,
          tooltip: {
                valueDecimals: 2
            }

      },{
          yAxis: 0,
          name: 'NASDAQ 100',
          data: {{ sp500_series | safe}},
          color: 'green',
          showInLegend:true,
          tooltip: {
                valueDecimals: 2
            }

      }]
  });


</script>
<div id="container1" style="height: 100%; width:90%";position:absolute;>
<div class='col-md-12';>
    <div class="panel panel-default";style="height: 400; width:100";>
        <div class="panel-heading">
            <h3 class="panel-title">Indicator Details and Other Charts</h3>
        </div>
        <div class="panel-body">
            <div class="tabbable-line">
                <ul class="nav nav-tabs">

        <li class="#active">
            <a href="#detail" data-toggle="tab" aria-expanded="true">
                Indicator Detail
            </a>
        </li>

</ul>
<div class="tab-content">
    <div class="tab-pane fade active in" id="detail">
           <div class="well">
                 <h4>
                     <b>
                           Time Frame:

                                Medium-Term

                        </b>
                    </h4>
                    <h4>
                        <b>
                            Update Schedule:

                                Daily by 6:00 PM EST

                        </b>
                    </h4>

                    <h4>
                        <b>
                            Source:

                                Resilient Capital

                        </b>
                    </h4>

                </div>


        <h4>
            <b>Construction:</b>
        </h4>
        <p>The Smart Money Confidence and Dumb Money Confidence indices are a unique innovation that allows subscribers to see, in one quick glance, what the "good" market timers are doing with their money compared to what "bad" market timers are doing. </p>

<p>Our Confidence indices use mostly real-money gauges - there are few opinions involved here.
Generally, we want to follow the Smart Money traders when they reach an extreme - we want to bet on a market rally when they are confident of rising prices, and we want to be short (or in cash) when they are expecting a market decline. The higher the confidence number, the more aggressively we should be looking for higher prices.</p>

<p>Examples of some Smart Money indicators include the OEX put/call and open interest ratios, commercial hedger positions in the equity index futures, and the current relationship between stocks and bonds.</p>

<p>In contrast to the Smart Money, we want to do the opposite of what the Dumb Money is doing when they are at an extreme.  These traders have proven themselves over history to be bad at market timing.  They get very bullish after a market rally, and bearish after a market fall.  By the time the majority of them catch on to a trend, it?s too late - the trend is about to reverse.  It tells us how confident we should be in selling the market.
 </p>
<p>Examples of some Dumb Money indicators include the equity-only put/call ratio, the flow into and out of the Rydex series of index mutual funds, and small speculators in equity index futures contracts. We also chart the spread between the Smart Money and Dumb Money.  This gives us a quick view of the difference between the two groups of traders.  Because the "dumb money" follows trends, and the "smart money" generally goes against trends, the "dumb money" is usually correct during the meat of the trend.  So when the Dumb Money Confidence is higher than the Smart Money Confidence, that means sentiment is positive.</p>

<p>When it becomes too positive, however, then sentiment has reached an extreme, and stocks often run into trouble.  This usually happens because the Dumb Money rises above 60%, and the Smart Money drops below 40%.  That is a warning sign for stocks.</p>

<p>When the Dumb Money is below the Smart Money, then sentiment is negative and stocks are usually struggling.  It's best to be defensive at times like this.  However, when sentiment becomes too negative, then stocks are often poised to rally over the next 1-3 months.  This usually occurs because the Dumb Money has dropped below 40% and the Smart Money has risen above 60%.</p>

<p>What is considered "smart" is simply based on an indicator's historical record at extremes.  If an indicator is usually showing excessive pessimism near a market peak, and excessive optimism near a market bottom, then that indicator will be included in our Smart Money calculation.  And if it consistently shows too much pessimism near a low and too much optimism near a high, it will be considered Dumb Money.
</p>
<p>Confidence indices are presented on a scale of 0% to 100%.  When the Smart Money Confidence is at 100%, it means that those most correct on market direction are 100% confident of a rising market?and we want to be right alongside them.  When it is at 0%, it means that these good market timers are 0% confident in a rally, and we want to be in cash or even short when confidence is very low. </p>

<p>We can use the Dumb Money Confidence in a similar, but opposite, manner.  For example, if the Dumb Money Confidence is at 100%, then that means that these bad market timers are supremely confident in a market rally.  And history suggests that when these traders are confident, we should be very, very worried that the market is about to decline.  When the Dumb Money Confidence is at 0%, then from a contrary perspective we should be concentrating on the long side, expecting these traders to be wrong again and the market to rally. </p>

<p>In practice, our Confidence Indexes rarely get below 30% or above 70%. </p>

    </div>
</div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

Resilientcapitalstockdjango-master/templates/registration.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}